name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
   runs-on: ubuntu-22.04
   steps:
     - uses: actions/checkout@v4
     - run: docker compose up
     - if: success()
       run: echo success
     - if: failure()
       run: echo failure
